replicaCount: 1

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

image:
  name: nginx:1.11
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: "default"
fullnameOverride: "default"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

env:
  open: []
secretEnv: []
  # - secretName: ""
  #   secretKeys: ""
  #   EnvName: ""

vault:
  enabled: false

ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.choco.kz
      paths:
        - /
  tls:
    - secretName: chart-example-tls
      hosts:
        - chart-example.choco.kz

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# - name: brox-dev-media
#   mountPath: /code/media  

# - name: brox-dev-media
#   persistentVolumeClaim:
#     claimName: brox-dev-media

configMap:
  enabled: false
configMapName: 'application.yml: |-'
configMapYaml:
  spring:
    main:
      banner-mode: off

nodeSelector: []

tolerations: []

affinity: {}

cronjobs: []
