{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
{{ .Values.configMapName | indent 2 }}
{{- with .Values.configMapYaml }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
