apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  labels:
{{ include "app.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.ports }}
  ports:
{{- end }}
{{- if .Values.ports }}
{{ toYaml .Values.ports | indent 4}}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
