{{- if .Values.secrets}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.nameOverride }}-secret
  annotations:
    checksum/secrets: {{ printf "%v" .Values.secrets | sha256sum }}
    helm.sh/hook: 'pre-install,pre-upgrade'
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: '-3'
spec:
  provider: vault
  secretObjects:
    - data:
        {{- range $envVar := .Values.secrets }}
        - objectName: {{ $envVar | quote }}
          key: {{ $envVar | quote }}
        {{- end }}
      secretName: {{ include "app.fullname" . }}-secrets
      type: Opaque
  parameters:
    objects: |
      {{- range $envVar := $.Values.secrets }}
      - objectName: {{ $envVar | quote }}
        secretPath: "kv/data/{{ $.Values.environment }}/{{ $.Values.nameOverride }}"
        secretKey: {{ $envVar | quote }}
      {{- end }}
    roleName: {{ include "app.fullname" . }}
    vaultAddress: {{ .Values.vaultAddress | default "http://vault.vault.svc:8200" }}
{{- end -}}